/*
 * PWM_config.h
 *
 *  Created on: Sep 21, 2021
 *      Author: 20114
 */

#ifndef MCAL_PWM_PWM_CONFIG_H_
#define MCAL_PWM_PWM_CONFIG_H_
/*	Options:
 * 		-ENABLE
 * 		-DISABLE
 */
#define OC0_STATE	ENABLE
/*	Options:
 * 		-ENABLE
 * 		-DISABLE
 */
#define OC1A_STATE	ENABLE
/*	Options:
 * 		-ENABLE
 * 		-DISABLE
 */
#define OC1B_STATE	DISABLE
/*	Options:
 * 		-ENABLE
 * 		-DISABLE
 */
#define OC2_STATE	ENABLE

/*	Options:
 * 		-FAST_PWM
 * 		-PHASE_CORRECT_PWM
 */
#define OC0_MODE	FAST_PWM


/*	Options:
 	 	PWM_PHASE_CORRECT_8BIT
		PWM_PHASE_CORRECT_9BIT
		PWM_PHASE_CORRECT_10BIT
		PWM_FAST_8BIT
		PWM_FAST_9BIT
		PWM_FAST_10BIT
		PWM_PHASE_FRQ_CORRECT_ICR1
		PWM_PHASE_FRQ_CORRECT_OCR1A
		PWM_PHASE_CORRECT_ICR1
		PWM_PHASE_CORRECT_OCR1A
		PWM_FAST_ICR1
		PWM_FAST_OCR1A
 */
#define OC1A_MODE	PWM_FAST_ICR1

/*	Options:
 	 	PWM_PHASE_CORRECT_8BIT
		PWM_PHASE_CORRECT_9BIT
		PWM_PHASE_CORRECT_10BIT
		PWM_FAST_8BIT
		PWM_FAST_9BIT
		PWM_FAST_10BIT
		PWM_PHASE_FRQ_CORRECT_ICR1
		PWM_PHASE_FRQ_CORRECT_OCR1A
		PWM_PHASE_CORRECT_ICR1
		PWM_PHASE_CORRECT_OCR1A
		PWM_FAST_ICR1
		PWM_FAST_OCR1A
 */
#define OC1B_MODE	PWM_FAST_ICR1

/*	Options:
 * 		-FAST_PWM
 * 		-PHASE_CORRECT_PWM
 */
#define OC2_MODE	FAST_PWM


#endif /* MCAL_PWM_PWM_CONFIG_H_ */
